SELECT DISTINCT
        WMH.WAREHOUSE_NAME
        ,sum(WMH.CREDITS_USED_COMPUTE) as TOTAL_CREDITS_USED
from KIV.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY WMH
where WMH.START_TIME between '2022-01-01' and '2022-01-31' group by 1 order by 1 asc
