SELECT
         'Replication' AS WAREHOUSE_GROUP_NAME,
         'USER' as user_name
        ,DATABASE_NAME AS WAREHOUSE_NAME
        ,RUH.START_TIME
        ,RUH.END_TIME
        ,RUH.CREDITS_USED
        --,1.00 as CREDIT_PRICE
        --,(1.00*RUH.CREDITS_USED) AS DOLLARS_USED
        ,'ACTUAL COMPUTE' AS MEASURE_TYPE
from    KIV.ACCOUNT_USAGE.REPLICATION_USAGE_HISTORY RUH
