SELECT
        'Auto Clustering' AS WAREHOUSE_GROUP_NAME
        ,DATABASE_NAME || '.' || SCHEMA_NAME || '.' || TABLE_NAME AS WAREHOUSE_NAME
        ,CAST(ACH.START_TIME as DATE) as date_used
        --,ACH.END_TIME
        ,sum(ACH.CREDITS_USED)
        --,1.00 as CREDIT_PRICE
        --,(1.00*ACH.CREDITS_USED) AS DOLLARS_USED
        --,'ACTUAL COMPUTE' AS MEASURE_TYPE
from    KIV.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY ACH group by 3, 2 order by 3
